base_url = "https://clip.citrusea.cc"
[book]
title = "Citrusea's Clip"
description = "Citrusea's Clip"
src = "content"
language = "zh"
authors = ["Jamyeins"]

[output.html]
git-repository-url = "https://github.com/Jamyein/clip"
#edit-url-template = "https://github.com/Jaymein/clip/edit/main/{path}"
additional-css = ["custom.css"]

[output.html.search]
enable = false

[output.markdown]
enable = true

[mail]
# false will diasble mail sending
enable = false
from_email = "bot@owenyoung.com"
from_name = "Owen"
# you can set the mailjet contact list id here
# mailjet_contact_list_id = "17669"
# or directly set the to_email, seperated by comma
# or your can also set the environment variable TO_EMAIL
to_email = ""
